export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_BY_ID = 'FETCH_PROFILE_BY_ID';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const FETCH_TEAMS = 'FETCH_TEAMS';
export const FETCH_SCHOOLS = 'FETCH_SCHOOLS';
export const FETCH_FACILITIES = 'FETCH_FACILITIES';
